Algoritmo "exercicio7"
// 
//  
// Descrição   : leia um numero inteiro e mostre o resto a divisão dele por 2
// Autor(a)    : Nahomy Natera
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
 n1: inteiro
 divisao: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o numero: ")
   leia(n1)
   
   divisao <- n1/2
   
   escreva("A divisão é: ", divisao)

Fimalgoritmo