Algoritmo "exercicio8"
// 
//  
// Descrição   : leia dos numeros e calcule o primeiro elevado ao segundo
// Autor(a)    : Nahomy Natera
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
n1, n2: inteiro
elevado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o primeiro numero: ")
   leia(n1)
   escreva("Digite o segundo numero: ")
   leia(n2)
   
   elevado <- n1^n2
   
   escreva("O numero elevado é: ", elevado)
   
   

Fimalgoritmo