Algoritmo "Exercicio_11"
// 
//  
// Descrição   : Define a Media e ve se é Aprovado ou Reprovado
// Autor(a)    : Nahomy Natera
// Data atual  : 05/03/2026
Var
// Seção de Declarações das variáveis 
num1:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite seu numero: ")
leia(num1)
se(num1 > 7)entao
escreval("Vc esta Aprobado!")
senao
se(num1 < 7)entao
escreval("Vc ta Reprovado!")

fimse
fimse
Fimalgoritmo