Algoritmo "Exercicio_10"
// 
//  
// Descrição   : Define qual é o numero maior
// Autor(a)    : Nahomy Natera
// Data atual  : 05/03/2026
Var
// Seção de Declarações das variáveis 
num1:inteiro
num2:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o primeiro numero: ")
leia(num1)
escreva("Digite o segundo numero: ")
leia(num2)
se(num1 > num2) entao
escreva("O maior número é: ", num1)
senao
se(num2 > num1) entao
escreva("O maior número é: ", num2)
senao
escreva("Os números são iguais.")

fimse
fimse
Fimalgoritmo