Algoritmo "Exercicio_13"
// 
//  
// Descrição   : Define numero positivo, negativo e zero
// Autor(a)    : Nahomy Natera
// Data atual  : 05/03/2026
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o numero: ")
leia(num)
se(num > 1)entao
   escreva("O numero é positivo!")
senao
se(num < -1)entao
   escreva("O numero é negativo!")
senao
se(num = 0)entao
   escreva("O numero é 0")

fimse
fimse
fimse
Fimalgoritmo