Algoritmo "Exercio_15"
// 
//  
// Descrição   : verificação de intervalo
// Autor(a)    : Nahomy Natera
// Data atual  : 05/03/2026
Var
// Seção de Declarações das variáveis 
intervalo:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva("Digite o horario: ")
    leia(intervalo)
se(intervalo >= 10) e (intervalo <= 50)entao
    escreva("vc tá no horario de intervalo")
senao
    escreva("vc não ta não horario de intervalo")

FIMSE
Fimalgoritmo