Algoritmo "exercicio 9"
// 
//  
// Descrição   : percebe qual é par e qual é impar
// Autor(a)    : Nahomy Natera
// Data atual  : 27/02/2026
Var
// Seção de Declarações das variáveis
num:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite un numero: ")
leia(num)

se(num%2=0)entao
escreva("Seu numero é par!")
senao
escreva("Seu numero é impar!")
fimse

Fimalgoritmo